### ISSUE TITLE
Getting error when installing via yarn

### ISSUE THREAD

**Issue by itsaboutcode** [vasilevich/sync-yarnlock-into-packagejson#1]
$ yarn add -g sync-yarnlock-into-packagejson
yarn add v1.3.2
error Missing list of packages to add to your project.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by vasilevich** [comment]
Hi, I have solved this issuse by changing the name of the package to 
syncyarnlock
please try 
`yarn add global syncyarnlock`

reopen the issuse if there is another problem
best of luck!
