### ISSUE TITLE
Modify to parse yarn.lock only without depending on node_modules

### ISSUE THREAD

**Issue by iyobo** [vasilevich/sync-yarnlock-into-packagejson#15]
This tool is great! But It seems it does not purely determine versions from yarn.lock alone but also tries to check node_modules.

Is it possible to have it independently work with yarn.lock alone?

**Comment by vasilevich** [comment]
Hello, yes in the past it was possible,  if you want you can try version 1.0.18

### **to install it use:**
#### npm
`npm install syncyarnlock@1.0.18`
or
#### yarn
`yarn add syncyarnlock@1.0.18`


Please feel free to reopen this issue if I haven't solved your problem.
if you think this should be part of the current module let me know or make a pull request and I will consider it.

Thanks for your time.
