### ISSUE TITLE
No newline at end of generated json file

### ISSUE THREAD

**Issue by cpxPratik** [vasilevich/sync-yarnlock-into-packagejson#4]
When I do `syncyarnlock -sk` or `syncyarnlock`, generated json file does not have newline at end of file, which is not recommended and gives warning on git, can be an issue when doing `cat` etc.

**Comment by vasilevich** [comment]
Hey,
Thank you for reporting the issue,
if you want to achieve -s and -k function at the same time, please try to write -s -k instead, I am not sure if -sk can work.
now regarding the newline, as you asked I added it.
I didn't test it tho but it should work.
I'll close the issue please feel free to reopen it if you run into issues or open a new issue if other things arise.

best of luck.

**Comment by cpxPratik** [comment]
@vasilevich It does work with `-sk` on zsh here like `git commit -am`. You have not published latest to npm so cannot test the fix.

**Comment by cpxPratik** [comment]
@vasilevich Package is not published properly. There are no js files or executables on `~/.config/yarn/global/node_modules/syncyarnlock` for 1.0.10.

**Comment by vasilevich** [comment]
@cpxPratik I apologize again, i must of been not focused, pushed a new fix right now with JS files included into the package.
thank you for your patience.
