### ISSUE TITLE
Possible to prefix version number with tilde? (~)

### ISSUE THREAD

**Issue by ashleyw** [vasilevich/sync-yarnlock-into-packagejson#8]
Is it possible to prefix version numbers in the package.json file with a tilde, indicating it can use any patch version of that package?

Thanks!

**Comment by vasilevich** [comment]
@ashleyw hey, how about I add an optional commandline parameter --tilide  and this will in turn make all package numbers tlide if I understand correctly for example:
this:
`"dependencies": {
    "commander": "2.11.0",
    "yarn-lock-convert": "1.0.2"
  }`
 would become:
`"dependencies": {
    "commander": "~2.11.0",
    "yarn-lock-convert": "~1.0.2"
  }`

**Comment by reini-1** [comment]
I think, changing the regex `currentVersion.match(/(^[\^><=]+)/);` to `currentVersion.match(/(^[~^><=]+)/);` would be fine.
See https://github.com/npm/node-semver/blob/master/README.md#tilde-ranges-123-12-1
Thanks in advance.

**Comment by n8tb1t** [comment]
Hi, very useful project, it's upsetting that yarn doesn't have something similar build-in :(

**Comment by vasilevich** [comment]
Hey since i accepted the pull request i will close this issue. Feel free to reopen if needed.
